---
- name: Roles, Group and Tools
  hosts: all
  connection: local
  become: true
  vars:
    docker_users:
      - panda
      - vagrant

  roles:
  - packages
  - user
  - geerlingguy.docker
  - christiangda.awscli
  - christiangda.awscli_configure
  - diodonfrost.terraform

